### PR TITLE
Create chat

### PR DESCRIPTION
**Pull request by houstondapaz**
Hi, how did you discover the modules are 'bgiachiigg', 'bfifcddbbg', 'bbcaggdbc'?

### CODE REVIEW

**Comment by tulir** [comment]
First I prettified both new and old whatsapp web app.js files, then looked for the old module ids (`'ebfhaccdcd', 'djijebjjdh', 'bfggaciiij'`) in the old source. I found some unobfuscated names in those old modules, so then I just looked for those same names in the new source and used the resulting module ids.

**Comment by houstondapaz** [comment]
First thanks for reply.
How do you get the old whatsapp web.js?

**Comment by tulir** [comment]
Hmm, I don't actually remember, I might have found a suitably old app.js file in some random github thread. I think the module IDs don't change all the time, they probably changed something in their build system (e.g. updating webpack) which is what caused the most recent change.

All the old app.js files are available under web.whatsapp.com, but obviously not indexable. Based on my bash history, I think I used https://web.whatsapp.com/app.f2d64e26d366144085e4.js and https://web.whatsapp.com/app.5b1c3ef6635fc7ae23c7.js (not sure which one is the new one)

**Comment by houstondapaz** [comment]
I tried to run with the actual modules names `['bgiachiigg', 'bfifcddbbg', 'bbcaggdbc']` but the generated proto is too short.


I don't know how to discover the right modules

**Comment by tulir** [comment]
Weird, I'm pretty sure the module names haven't changed. If I run `node index.js` in `doc/spec/protobuf-extractor` on the `fix-protobuf-extractor` branch, it gets the correct schema which doesn't seem to have changed since I made the branch and generated `doc/spec/def.proto`.

The app.js file it finds is https://web.whatsapp.com/app.33a5aaab8c189f3ff681.js, which seems to be the same as if you go to web.whatsapp.com in a browser.

**Comment by houstondapaz** [comment]
Forgets! I was overwriting the same file over the loop
Thank you

Do you use protoc to compile?

**Comment by tulir** [comment]
Yes, `protoc --go_out=. def.proto` which requires `protoc-gen-go`

https://github.com/tulir/go-whatsapp/tree/master/binary/proto

**Pull request closed without merging**
